ZH/ZH/Models/ZHEF/EmployeeTable.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZH.Models.ZHEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeTable()
        {
            this.FoodTables = new HashSet<FoodTable>();
        }
    
        public int Id { get; set; }
        public string Location { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string Username { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FoodTable> FoodTables { get; set; }
    }
}

ZH/ZH/Models/ZHEF/NGOTable.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZH.Models.ZHEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGOTable
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string Username { get; set; }
    }
}

ZH/ZH/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ZH.Models.ZHEF;

namespace ZH.Controllers
{
    public class EmployeeController : Controller
    {
        // GET: Employee
        public ActionResult Index()
        {
            return View();
        }






        [HttpGet]
        public ActionResult Login()
        { 
            return View(); 
        }
        






        [HttpPost]
        public ActionResult Login(string Username, string Password) 
        {
            var db = new ZHEntities();
            EmployeeTable employeeTable = (from employee in db.EmployeeTables
                                           where employee.Username.Equals(Username) &&
                                           employee.Password.Equals(Password)
                                           select employee).SingleOrDefault();
            


            if (employeeTable == null)
            {

                TempData["msg"] = "Employee not found";
                return View();
            }
            else
            {
                var employeeLogged = (from employee in db.EmployeeTables
                                      where employee.Username.Equals(Username)
                                      select employee).SingleOrDefault();

                var employeeId = employeeLogged.Id;
                Session["employeeLogged"] = employeeId;
                return RedirectToAction("Dashboard");
            }
        }







        [HttpGet]
        public ActionResult Logout()
        {
            Session.Remove("employeeLogged");
            return RedirectToAction("Login");
        }






        [HttpGet]
        public ActionResult Dashboard()
        {
            return View();
        }








        [HttpGet]
        public ActionResult EmployeeDetails()
        {
            var db = new ZHEntities();
            var employeedetails = db.EmployeeTables.ToList();
            return View(employeedetails);

        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }




        [HttpPost]
        public ActionResult Create(EmployeeTable employeeTable)
        {
            var db = new ZHEntities();
            db.EmployeeTables.Add(employeeTable);
            db.SaveChanges();
            TempData["msg"] = "Your employee profile has been created";
            return RedirectToAction("EmployeeDetails");
        }







        [HttpGet]
        public ActionResult Edit(int id)
        {
            var db = new ZHEntities();
            var emp = (from  employee in db.EmployeeTables
                       where employee.Id == id
                       select employee).FirstOrDefault();
            return View(emp);
        }







        [HttpPost]
        public ActionResult Edit(EmployeeTable employeeTable)
        {
            var db = new ZHEntities();
            var emp = (from employee in db.EmployeeTables
                       where employee.Id == employeeTable.Id
                       select employee).SingleOrDefault();

            emp.Name = employeeTable.Name;
            emp.Username = employeeTable.Username;
            emp.Password = employeeTable.Password;
            emp.Location = employeeTable.Location;
            db.SaveChanges();


            TempData["msg"] = "Employee details has been update";
            return RedirectToAction("EmployeeDetails");
        }







        [HttpGet]
        public ActionResult Delete(int id)
        {
            var db = new ZHEntities();
            var emp = (from employee in db.EmployeeTables
                       where employee.Id == id
                       select employee).FirstOrDefault();

            db.EmployeeTables.Remove(emp);
            db.SaveChanges();
            TempData["msg"] = "Employee details has been removed";
            return RedirectToAction("EmployeeDetails");
        }







        [HttpGet]
        public ActionResult CollectRequest()
        {
            var db = new ZHEntities();
            var employeeLogged = Convert.ToInt32(Session["employeeLogged"]);
            var emp = (from employee in db.FoodTables
                       where employee.AssignedEmp == employeeLogged
                       select employee).ToList();

            return View(emp);
        }















        public ActionResult CollectionCompleted(int id)
        {
            var db = new ZHEntities();
            var emp = (from employee in db.FoodTables
                       where employee.Id==id
                       select employee).FirstOrDefault();


            emp.Status = "Collection Done";
            db.SaveChanges();
            return RedirectToAction("CollectRequest");
        }





    }
}

ZH/ZH/Controllers/NGOController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ZH.Models.ZHEF;

namespace ZH.Controllers
{
    public class NGOController : Controller
    {
        // GET: NGO
        public ActionResult Index()
        {
            return View();
        }







        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }







        //login form database and checking if null
        [HttpPost]
        public ActionResult Login(string Username, string Password)
        {
            var db = new ZHEntities();
            NGOTable ngotable = (from NGOTable in db.NGOTables
                                 where NGOTable.Username.Equals(Username) &&
                                       NGOTable.Password.Equals(Password)
                                 select NGOTable).FirstOrDefault();


            if (ngotable == null)
            {
                TempData["msg"] = "Username or password not found";
                return View();
            }
            else
            {
                var NGOLogged = (from NGOTable in db.NGOTables
                                 where NGOTable.Username.Equals(Username)
                                 select NGOTable).SingleOrDefault();

                var NGOId = NGOLogged.Id;
                Session["NGOLogged"] = NGOId;
                return RedirectToAction("Dashboard");
            }

        }





        [HttpGet]
        public ActionResult Logout() {

            Session.Remove("NGOLogged");
            return RedirectToAction("Login");
        }









        [HttpGet]
        public ActionResult Dashboard()
        {
            return View();
        }










        //list of collection request
        public ActionResult CollectRequest()
        {
            var db = new ZHEntities();
            var foodtable = db.FoodTables.ToList();
            return View(foodtable);
        }











        [HttpGet]
        public ActionResult Employee(int id)
        {
            var db = new ZHEntities();
            var emp = (from collection in db.FoodTables
                       where collection.Id==id
                       select collection).SingleOrDefault();
            return View(emp);
        }









        [HttpPost]
        public ActionResult Employee(int Id, int Employee)
        {
            var db = new ZHEntities();
            var emp = (from collection in db.FoodTables
                       where collection.Id == Id
                       select collection).SingleOrDefault();
            db.SaveChanges();

            TempData["msg"] = "Your request is accepted";
            return RedirectToAction("Dashboard");
        }

    }

}

ZH/ZH/Views/NGO/CollectRequest.cshtml
@model IEnumerable<ZH.Models.ZHEF.FoodTable>
@{
    ViewBag.Title = "Request Collection";
}

<h2 style="color:white">Request Collection</h2>

@Styles.Render("~/Content/Login.css")
@Styles.Render("~/Content/List.css")




<body>
    <section>
        <div class="layout">

            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.FoodType)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Quantity)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Status)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.AssignedEmp)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.RequestedRes)
                    </th>
                    <th>
                        Restuarant Location
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.FoodType)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Quantity)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Status)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.EmployeeTable.Name)
                        </td>
                        <td>
                            @item.ResturentTable.Name
                        </td>
                        <td>
                            @item.ResturentTable.Location
                        </td>
                        <td>
                            <button type="button" class="btn btn-warning" onclick="location.href='@Url.Action("Employee", "NGO", new { id = item.Id })'">Assign Employee</button>
                        </td>
                    </tr>
                }

            </table>
            </div>

        <div class="btn-group">
            <a href="/NGO/Dashboard" class="btn btn-warning">Back to Dashboard</a>
        </div>

</section>
</body>

ZH/ZH/Views/NGO/Dashboard.cshtml
@{
    ViewBag.Title = "Dashboard";
}

<h2 style="color:white">NGO Dashboard</h2>

@Styles.Render("~/Content/Login.css")
@Styles.Render("~/Content/Dashboard.css")

<body>
    <section>
        <div class="layout">

            <div class="btn-group">
                <a href="/Employee/EmployeeDetails" class="btn btn-primary">Manage Employees</a>
                <a href="/Resturent/ManageResturent" class="btn btn-success">Manage Restaurants</a>
                <a href="/NGO/CollectRequest" class="btn btn-warning">Collection Requests</a>
                <a href="/NGO/Logout" class="btn btn-danger">Logout</a>
            </div>

         </div>
    </section>
</body>

ZH/ZH/Views/NGO/Employee.cshtml
@model ZH.Models.ZHEF.FoodTable
@{
    ViewBag.Title = "Employee";
}

@Styles.Render("~/Content/Edit.css")
@Styles.Render("~/Content/List.css")

@using (Html.BeginForm("Employee", "NGO"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Assign Employee For Collection</h4>

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            <div class="col-md-10">
                @Html.EditorFor(model => model.AssignedEmp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AssignedEmp, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
            <br />
            <br />
                <div>
                    <a href="/NGO/CollectRequest" class="btn btn-warning">Back to Request List</a>
                </div>
        </div>
    </div>
}

ZH/ZH/Views/NGO/Login.cshtml
@{
    ViewBag.Title = "NGO Login";
}

<body>

    @Styles.Render("~/Content/Login.css")

    <form method="post" action="" class="form">
        <div class="text-danger">@TempData["msg"]</div>

        <h3>ZH NGO</h3>
        <input class="form-control" type="text" name="Username" value="" placeholder="Username" /><br>
        <input class="form-control" type="password" name="Password" value="" placeholder="Password" /><br>
        <input class="btn btn-primary" type="submit" name="submit" value="Login" /><br>

    </form>
</body>