ZH/ZH/Models/ZHEF/ResturentTable.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZH.Models.ZHEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResturentTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ResturentTable()
        {
            this.FoodTables = new HashSet<FoodTable>();
        }
    
        public int Id { get; set; }
        public string Location { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string Username { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FoodTable> FoodTables { get; set; }
    }
}

ZH/ZH/Controllers/ResturentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ZH.Models.ZHEF;

namespace ZH.Controllers
{
    public class ResturentController : Controller
    {
        // GET: Resturent
        public ActionResult Index()
        {
            return View();
        }



        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }



        [HttpPost]
        public ActionResult Login(string Username, string Password)
        {
            var db = new ZHEntities();
            ResturentTable resturentTable = (from resturent in db.ResturentTables
                                             where resturent.Username.Equals(Username) &&
                                             resturent.Password.Equals(Password)
                                             select resturent).FirstOrDefault();


            if (resturentTable == null)
            {
                TempData["msg"] = "Resturent username and password not found";
                return View();
            }
            else
            {
                var resturentLogged = (from resturent in db.ResturentTables
                                       where resturent.Username.Equals(Username)
                                       select resturent).FirstOrDefault();

                var resturentId = resturentLogged.Id;
                Session["resturentLogged"] = resturentId;
                return RedirectToAction("Dashboard");
            }
        }













        [HttpGet]
        public ActionResult Logout()
        {
            Session.Remove("resturentLogged");
            return RedirectToAction("Login");
        }









        [HttpGet]
        public ActionResult Dashboard()
        {
            return View();
        }






        [HttpGet]
        public ActionResult RequestCollection()
        {
            var db = new ZHEntities();
            var resturentLogged = Convert.ToInt32(Session["resturentLogged"]);
            var res = (from resturent in db.FoodTables
                       where resturent.RequestedRes == resturentLogged
                       select resturent).ToList();

            return View(res);
        }








        [HttpGet]
        public ActionResult CreateRequest()
        {
            return View();
        }










        [HttpPost]
        public ActionResult CreateRequest(string Foodtype, string Quantity)
        {
            var db = new ZHEntities();
            FoodTable foodTable = new FoodTable();
            foodTable.FoodType = Foodtype;
            foodTable.Quantity = Quantity;
            foodTable.Quantity = Quantity;
            foodTable.RequestedRes = Convert.ToInt32(Session["resturentLogged"]);
            foodTable.Status = "Pending";
            db.FoodTables.Add(foodTable);
            db.SaveChanges();
            TempData["msg"] = "Request for food collection has been confirmed";
            return RedirectToAction("RequestCollection");
        }











        [HttpGet]
        public ActionResult Delete(int id)
        {
            var db = new ZHEntities();
            var ft = (from food in db.FoodTables
                       where food.Id == id
                       select food).SingleOrDefault();



            db.FoodTables.Remove(ft);
            db.SaveChanges();
            TempData["msg"] = "Request for food collection has been removed";
            return RedirectToAction("CollectRequest");

        }




        [HttpGet]
        public ActionResult ManageResturent()
        {
            var db = new ZHEntities();
            var resturent = db.ResturentTables.ToList();
            return View(resturent);
        }






        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }





        [HttpPost]
        public ActionResult Create(ResturentTable resturentTable)
        {
            var db = new ZHEntities();
            db.ResturentTables.Add(resturentTable);
            db.SaveChanges();
            TempData["msg"] = "resturent has been added to the system";
            return RedirectToAction("ManageResturent");
        }







        [HttpGet]
        public ActionResult Edit(int id)
        {
            var db = new ZHEntities();
            var resturentTable = (from resturent in db.ResturentTables
                       where resturent.Id == id
                       select resturent).SingleOrDefault();
            return View(resturentTable);

        }






        [HttpPost]
        public ActionResult Edit(ResturentTable resturentTable)
        {
            var db = new ZHEntities();
            var res = (from resturent in db.ResturentTables
                       where resturent.Id == resturentTable.Id
                       select resturent).SingleOrDefault();

            res.Name = resturentTable.Name;
            res.Username = resturentTable.Username;
            res.Password = resturentTable.Password;
            res.Location = resturentTable.Location;
            db.SaveChanges();


            TempData["msg"] = "Resturent has been added to the system";
            return RedirectToAction("ManageResturent");
        }









        [HttpGet]
        public ActionResult DeleteResturent(int id)
        {
            var db = new ZHEntities();
            var res = (from resturent in db.ResturentTables
                       where resturent.Id == id
                       select resturent).SingleOrDefault();


            db.ResturentTables.Remove(res);
            db.SaveChanges();

            TempData["msg"] = "Resturent has been deleted";
            return RedirectToAction("ManageResturent");
        }



    }
}

ZH/ZH/Views/Resturent/Create.cshtml
@model ZH.Models.ZHEF.ResturentTable

@{
    ViewBag.Title = "Create";
}


@Styles.Render("~/Content/Edit.css")
@Styles.Render("~/Content/List.css")


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Restaurant Registration</h4>

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
                <br />
                <br />
                <div>
                    <a href="/Resturent/ManageResturent" class="btn btn-warning">Back to Restaurant List</a>
                </div>
            </div>
        </div>
    </div>
}

ZH/ZH/Views/Resturent/CreateRequest.cshtml
@model ZH.Models.ZHEF.FoodTable

@{
    ViewBag.Title = "CreateRequest";
}


<body>
    <form>

         @Styles.Render("~/Content/LoginCRR.css")

         @using (Html.BeginForm())
         {
            @Html.AntiForgeryToken()

          <div class="form-horizontal">
            <h2>Create Pick Request</h2>

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })


            <div class="form-group">
                @Html.LabelFor(model => model.FoodType, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FoodType, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FoodType, "", new { @class = "text-danger" })
                </div>
            </div>



            <div class="form-group">
                @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
                <br />
                <br />
                <div>
                    <a href="/Resturent/RequestCollection" class="btn btn-warning">Back to Request List</a>
                </div>
            </div>
        </div>
        }
    </form>
</body>

ZH/ZH/Views/Resturent/Dashboard.cshtml
@{
    ViewBag.Title = "Dashboard";
}

<h2 style="color:white">Restaurant Dashboard</h2>

@Styles.Render("~/Content/Login.css")
@Styles.Render("~/Content/Dashboard.css")

<body>
    <section>
        <div class="layout">

            <div class="btn-group">
                <a href="/Resturent/CreateRequest" class="btn btn-primary">Request Collection</a>
                <a href="/Resturent/RequestCollection" class="btn btn-warning">Request List</a>
                <a href="/Resturent/Logout" class="btn btn-danger">Logout</a>
            </div>

            </div>
    </section>
</body>

ZH/ZH/Views/Resturent/Edit.cshtml
@model ZH.Models.ZHEF.ResturentTable

@{
    ViewBag.Title = "Edit";
}


@Styles.Render("~/Content/Edit.css")
@Styles.Render("~/Content/List.css")


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>
            Edit Restaurant Details
        </h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

ZH/ZH/Views/Resturent/Login.cshtml
@{
    ViewBag.Title = "Restaurant Login";
}

<body>

    @Styles.Render("~/Content/Login.css")

    <form method="post" action="" class="form">
        <div class="text-danger">@TempData["msg"]</div>

        <h3>ZH RESTAURANT</h3>
        <input class="form-control" type="text" name="Username" value="" placeholder="Username" /><br>
        <input class="form-control" type="password" name="Password" value="" placeholder="Password" /><br>
        <input class="btn btn-primary" type="submit" name="submit" value="Login" /><br>

    </form>
</body>

ZH/ZH/Views/Resturent/ManageResturent.cshtml
@model IEnumerable<ZH.Models.ZHEF.ResturentTable>
@{
    ViewBag.Title = "ManageResturent";
}



@Styles.Render("~/Content/Login.css")
@Styles.Render("~/Content/List.css")





<body>
    <section>
        <div class="layout">

            <h2 style="color:black">Manage Resturent</h2>

            <p>
                <button type="button" class="btn btn-success" onclick="location.href='@Url.Action("Create", "Resturent")'">Create New Restaurant</button>
            </p>


            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Username)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Location)
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Username)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Location)
                        </td>


                        <td>
                            <button type="button" class="btn btn-warning" onclick="location.href='@Url.Action("Edit", "Resturent", new { id = item.Id })'">Edit</button>
                            <button type="button" class="btn btn-danger" onclick="location.href='@Url.Action("DeleteResturent", "Resturent", new { id = item.Id })'">Delete</button>
                        </td>
                    </tr>
                }

            </table>
        </div>

            <div class="btn-group">
                <a href="/NGO/Dashboard" class="btn btn-warning">Back to Dashboard</a>
            </div>

    </section>
</body>

ZH/ZH/Views/Resturent/RequestCollection.cshtml
@model IEnumerable<ZH.Models.ZHEF.FoodTable>

@{
    ViewBag.Title = "Request Collection";
}

@Styles.Render("~/Content/Login.css")
@Styles.Render("~/Content/List.css")


<body>
    <section>
        <div class="layout">

            <h2 style="color:black">Request Collection</h2>

            <p>
                <button type="button" class="btn btn-success" onclick="location.href='@Url.Action("CreateRequest", "Resturent")'">Create New Request</button>
            </p>


            <p>
                @TempData["message"]
            </p>
            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.FoodType)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Quantity)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Status)
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.FoodType)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Quantity)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Status)
                        </td>
                        <td>
                            <button type="button" class="btn btn-danger" onclick="location.href='@Url.Action("Delete", "Resturent", new { id = item.Id })'">Delete Request</button>
                        </td>
                    </tr>
                }
            </table>



            <div class="btn-group">
                <a href="/Resturent/Dashboard" class="btn btn-warning">Back to Dashboard</a>
            </div>
        
        </div>
    </section>
</body>